# Generated by Django 3.0.3 on 2020-03-19 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=255)),
                ('available', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
                ('uploaded', models.BooleanField(default=False)),
                ('original_hash', models.BinaryField(max_length=32, unique=True)),
                ('image_x', models.IntegerField()),
                ('image_y', models.IntegerField()),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('priority', models.FloatField(default=1)),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='image',
            constraint=models.CheckConstraint(check=models.Q(('uploaded', True), models.Q(('uploaded', False), ('deleted', True)), _connector='OR'), name='not_uploaded_must_delete'),
        ),
    ]
