# Generated by Django 3.0.3 on 2020-03-15 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_mgr', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='visible',
            new_name='deleted',
        ),
    ]
