# Generated by Django 3.0.3 on 2020-03-15 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_mgr', '0002_auto_20200314_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_x',
            field=models.IntegerField(default=2560),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='image_y',
            field=models.IntegerField(default=1920),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='original_hash',
            field=models.BinaryField(default=b'x', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='uploaded',
            field=models.BooleanField(default=True),
        ),
        migrations.AddConstraint(
            model_name='image',
            constraint=models.CheckConstraint(check=models.Q(('uploaded', True), models.Q(('uploaded', False), ('deleted', True)), _connector='OR'), name='not_uploaded_deleted'),
        ),
    ]
