# Generated by Django 3.0.3 on 2020-03-19 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_mgr', '0002_auto_20200319_1419'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='num_images',
            new_name='num_annotations',
        ),
    ]
