# Generated by Django 3.0.3 on 2020-03-15 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_mgr', '0003_auto_20200314_2030'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='image',
            name='not_uploaded_deleted',
        ),
        migrations.AlterField(
            model_name='image',
            name='original_hash',
            field=models.BinaryField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='uploaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='image',
            constraint=models.CheckConstraint(check=models.Q(('uploaded', True), models.Q(('uploaded', False), ('deleted', True)), _connector='OR'), name='not_uploaded_must_delete'),
        ),
    ]
