# Generated by Django 3.0.3 on 2020-03-19 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0003_auto_20200319_1039'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('reviewer', "Can review others' annotations."), ('account_manager', 'Can create accounts and reset passwords.')]},
        ),
    ]
