# Generated by Django 3.0.3 on 2020-03-19 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0004_auto_20200319_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_reset_token',
            field=models.BinaryField(max_length=16, null=True),
        ),
    ]
