# Generated by Django 3.0.3 on 2020-03-19 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0005_user_password_reset_token'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
