# Generated by Django 3.0.3 on 2020-02-15 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='upload_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
