# Generated by Django 3.0.3 on 2020-02-15 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('label_app', '0002_auto_20200215_0314'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
