# Generated by Django 3.0.3 on 2020-04-10 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label_app', '0002_annotation_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='comment',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
