# Generated by Django 3.0.3 on 2020-02-15 18:45

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models
from django.utils.timezone import utc
import label_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('label_app', '0004_annotation_polygon'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 2, 15, 16, 45, 58, 560090, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='polygon',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='polygon',
            name='points',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None, validators=[label_app.models.validate_is_points]),
        ),
    ]
