# Generated by Django 3.0.3 on 2020-03-19 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label_app', '0007_auto_20200215_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
