# Generated by Django 3.0.3 on 2020-03-19 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label_app', '0008_annotation_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='edit_version',
            field=models.IntegerField(default=0),
        ),
    ]
